---
name: "Build"
"on":
  pull_request:
    branches:
    - "master"
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v5"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "temurin"
        java-version: "17"
    - name: "Setup Gradle"
      uses: "gradle/actions/setup-gradle@v4"
      with:
        cache-read-only: false
        dependency-graph: "generate-and-submit"
        add-job-summary-as-pr-comment: "on-failure"
    - name: "Make gradlew executable"
      run: "chmod +x gradlew"
    - name: "Build with Gradle"
      run: "./gradlew build"
