---
name: "Update Changelog"
"on":
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  changelog:
    name: "Update Changelog"
    runs-on: "ubuntu-latest"
    if: "${{ !contains(github.event.head_commit.message, 'skip-snapshot') }}"
    steps:
    - uses: "release-drafter/release-drafter@master"
      id: "release"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
