---
name: "Update Changelog"
"on":
  push:
    branches:
    - "master"
jobs:
  changelog:
    name: "Update Changelog"
    runs-on: "ubuntu-latest"
    if: "${{ !contains(github.event.head_commit.message, 'skip-snapshot') }}"
    steps:
    - uses: "release-drafter/release-drafter@v6"
      id: "release"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
