---
name: "Release"
"on":
  release:
    types:
    - "released"
jobs:
  build:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "temurin"
        java-version: "17"
    - name: "Setup Gradle"
      uses: "gradle/actions/setup-gradle@v4"
      with:
        cache-read-only: false
    - name: "Validate version format"
      run: |
        [[ "${{ github.event.release.tag_name }}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    - name: "Publish with Gradle"
      run: |
        gradle -Psign-required=true publish -Pversion="${{ github.event.release.tag_name }}" -PmavenCentralUsername="${{ secrets.MAVEN_CENTRAL_USERNAME }}" -PmavenCentralPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}" -PsigningInMemoryKey="${{ secrets.GPG_PRIVATE_KEY_ARMORED }}" -PsigningInMemoryKeyPassword="${{ secrets.GPG_PASSPHRASE }}"
